name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: kitao/pyxel/.github/workflows/build.yml@main

  release:
    runs-on: macos-12
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download wheels
        uses: actions/download-artifact@v4.1.7
        with:
          name: pyxel-wheels
          path: dist

      - name: Get Pyxel version
        run: |
          PYXEL_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
          echo "PYXEL_VERSION=${PYXEL_VERSION}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Pyxel ${{ env.PYXEL_VERSION }}
          tag_name: ${{ github.ref }}
          files: dist/*

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true

      - name: Publish crates
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cd crates/pyxel-core
          cargo publish
          sleep 60
          cd ../pyxel-extension
          cargo publish

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Publish wheels
        run: |
          pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
